### ISSUE TITLE
Is this library maintained at all?

### ISSUE THREAD

**Issue by maroux** [google/python-spanner-orm#81]
Hi

I've opened a few issues and a few PRs but haven't heard anything on them. Just checking to see if this library is maintained at all and accepting changes?

Thanks!

**Comment by germanp173** [comment]
@akefeli I noticed you recently merged PR https://github.com/google/python-spanner-orm/pull/75. 
Can you look at the other great PRs @maroux has submitted? 
That would be very helpful and greatly appreciated!

**Comment by akefeli** [comment]
Hi marous and germanp173,

Sorry for lack of communication. We don't have our original maintainer anymore, that's why we have been slow to respond to PRs. We are still using the ORM internally in maintenance mode. I'm trying to find resources to get remaining PRs reviewed.

**Comment by germanp173** [comment]
@akefeli thanks for the heads up!
